// ReactApp/react-app/src/App.tsx
import './App.css'
import { useState } from 'react'

function App() {
  var [display, changeDisplay] = useState(false);
  var data: string[] = [];
  var str_data = localStorage.getItem("data");
  if (str_data) {
    data = JSON.parse(str_data);
    str_data = null;
  }
  var size = 6;
  var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

  function ranNum(max: number) {
    return Math.floor(Math.random() * (max));
  }

  var createData = function (num: number) {
    for (let i = 0; i < num; i++) {
      let str = "";
      for (let j = 0; j < size; j++) {
        str += chars.charAt(ranNum(chars.length));
      }
      data[i] = str;
    }
    localStorage.setItem("data", JSON.stringify(data));
    data = [];
    changeDisplay(false);
  }

  function clearData() {
    changeDisplay(false);
    localStorage.removeItem("data");
  }

  function updateData(num: number) {
    var str_data = localStorage.getItem("data");
    if (str_data !== null) {
      data = JSON.parse(str_data);
      str_data = null;
      if (num > data.length) {
        num = data.length;
      }
      for (let i = 0; i < num; i++) {
        let str = "";
        for (let j = 0; j < size; j++) {
          str += chars.charAt(ranNum(chars.length));
        }
        data[i] = str;
      }
      localStorage.setItem("data", JSON.stringify(data));
      data = [];
      changeDisplay(false);
    }
  }

  function displayData() {
    changeDisplay(true);
  }


  return (<>
    <header>
      <h1>React Test Application</h1>
    </header>
    <nav>
      <span className="nav">Test Cases: </span>
      <button onClick={() => { createData(1000) }}>Create 1000</button>
      <button onClick={() => { createData(5000) }}>Create 5000</button>
      <button onClick={() => { createData(10000) }}>Create 10000</button>
      <button onClick={() => { createData(50000) }}>Create 50000</button>
      <button onClick={() => { updateData(1000) }}>Update 1000</button>
      <button onClick={() => { updateData(5000) }}>Update 5000</button>
      <button onClick={() => { updateData(10000) }}>Update 10000</button>
      <button onClick={() => { updateData(50000) }}>Update 50000</button>
      <button onClick={() => { displayData() }}>Display Records</button>
      <button onClick={() => { clearData() }}>Delete Records</button>
    </nav>
    <div className="op">
      {display &&
        <div>
          {data.map((item: string, index: number) => <span key={index}>{item}</span>)}
        </div>}
    </div>
  </>
  )
}

export default App

// AngularApp/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'AngularApp';

  data: string[] = [];
  size = 6;
  chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

  ranNum(max: number) {
    return Math.floor(Math.random() * (max));
  }

  generateData(num: number) {
    for (let i = 0; i < num; i++) {
      let str = "";
      for (let j = 0; j < this.size; j++) {
        str += this.chars.charAt(this.ranNum(this.chars.length));
      }
      this.data[i] = str;
    }
    localStorage.setItem("data", JSON.stringify(this.data));
    this.data = [];
  }

  updateData(num: number) {
    var str_data = localStorage.getItem("data");
    if (str_data !== null) {
      this.data = JSON.parse(str_data);
      if (num > this.data.length) {
        num = this.data.length;
      }
      for (let i = 0; i < num; i++) {
        let str = "";
        for (let j = 0; j < this.size; j++) {
          str += this.chars.charAt(this.ranNum(this.chars.length));
        }
        this.data[i] = str;
      }
      localStorage.setItem("data", JSON.stringify(this.data));
      this.data = [];
    }
  }

  clearData() {
    this.data = [];
    localStorage.removeItem("data");
  }

  displayData() {
    var str_data = localStorage.getItem("data");
    if (str_data !== null) {
      this.data = JSON.parse(str_data);
    }
  }
}

<body>


    <header>
        <h1>Angular Test Application</h1>
    </header>
    <nav>
        <span class="nav">Test Cases: </span>
        <button (click)="generateData(1000)">Create 1000</button>
        <button (click)="generateData(5000)">Create 5000</button>
        <button (click)="generateData(10000)">Create 10000</button>
        <button (click)="generateData(50000)">Create 50000</button>
        <button (click)="updateData(1000)">Update 1000</button>
        <button (click)="updateData(5000)">Update 5000</button>
        <button (click)="updateData(10000)">Update 10000</button>
        <button (click)="updateData(50000)">Update 50000</button>
        <button (click)="displayData()">Display Records</button>
        <button (click)="clearData()">Delete Records</button>
    </nav>
    <div>
        @for(d of data; track $index) {
        <span>{{d}}</span>
        }
    </div>
</body>
